name: 'Continuous Testing'

on:
  workflow_call:

jobs:
  ct:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies (Ubuntu)
        run: |-
          sudo apt-get update
          sudo apt-get install -y g++-9

      - name: Setup node env ğŸ“¦
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Check out repository âœ¨ (non-dependabot)
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: actions/checkout@v3

      - name: Check out repository ğŸ‰ (dependabot)
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install dependencies ğŸš€
        run: npm i --prefer-offline --no-audit --omit=optional

      - name: Update apt-get ğŸš€
        run: sudo apt-get update -qq

      - name: Install required packages ğŸš€
        run: >-
          sudo apt-get install -qq libcairo2-dev libjpeg8-dev libpango1.0-dev
          libgif-dev build-essential g++ xvfb libgles2-mesa-dev libgbm-dev
          libxxf86vm-dev

      - name: Pull test data ğŸ“¦
        run: >-
          wget -O test_data.zip
          https://github.com/maptiler/tileserver-gl/releases/download/v1.3.0/test_data.zip

      - name: Prepare test data ğŸ“¦
        run: unzip -q test_data.zip -d test_data
        
      - name: Run tests ğŸ§ª
        run: xvfb-run --server-args="-screen 0 1024x768x24" npm test
